version: 0.1

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
  build:
    commands:
     - echo Build started on `date`
     - gradle build
artifacts:
  type: zip
  files:
    - 'build/distributions/purelandmusic-1.0-SNAPSHOT.zip'
