version: 0.1

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
      - export GRADLE_OPTS="-Dfile.encoding=utf-8"
  build:
    commands:
     - echo Build started on `date`
     - gradle build
     - sam package --template-file template.yaml --s3-bucket purelandcodebucket --output-template-file packaged-template.yaml
reports:
  junit-tests-group:
    files:
      - '**/*'
    base-directory: 'build/reports'
artifacts:
  files:
    - 'packaged-template.yaml'
    - 'configuration/description.txt'
    - 'configuration/*.json'
