AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  FunctionNameSuffix:
    Type: String
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://purelandcodebucket/531f1bf16f0c0ec1d4517abbc1be8a86
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      FunctionName:
        Fn::Sub: PureLandMusic-${FunctionNameSuffix}
      Handler: merits.funskills.pureland.v2.LambdaHandlerV2::handleRequest
      MemorySize: 512
      Policies:
      - AWSLambdaExecute
      - AmazonS3ReadOnlyAccess
      - Statement:
        - Action:
          - s3:GeneratePresignedUrl
          Effect: Allow
          Resource: arn:aws:s3:::purelandmusic
        Version: '2012-10-17'
      - Statement:
        - Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:GetRecords
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:UpdateTimeToLive
          - dynamodb:Query
          Effect: Allow
          Resource:
          - Fn::Sub: arn:aws:dynamodb:us-east-1:711575676778:table/pureLandTable-${FunctionNameSuffix}
          - Fn::Sub: arn:aws:dynamodb:us-east-1:711575676778:table/pureLandTable-${FunctionNameSuffix}/index/*
        Version: '2012-10-17'
      Runtime: java8
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
